# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- production

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install --save-dev @cucumber/cucumber
    npm install --save-dev @playwright/test
    npm install --save-dev @types/cucumber
    npm install --save-dev @types/node
    npm install --save-dev chai
    npm install --save-dev cross-env
    npm install --save-dev dotenv
    npm install --save-dev fs-extra
    npm install --save-dev multiple-cucumber-html-reporter
    npm install --save-dev playwright
    npm install --save-dev ts-node
    npm install --save-dev typescript
    npm install --save-dev winston

    npx playwright install

    npm test
  displayName: 'npm install and run'
