# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: windows-latest


variables:
  npm_packages_path: $(Pipeline.Workspace)/s/node_modules
  browser_path: $(Agent.WorkFolder)/chromium-1124


stages:
- stage: NodeJs
  displayName: 'Install Node.js'
  jobs:
    - job: InstallJob
      displayName: 'Node.js install job'
      steps:


      ## Node.js install
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'
          checkLatest: true
        displayName: Node.js installation


      - task: PowerShell@2
        inputs:
          targetType: inline
          script: |
            $Env:PLAYWRIGHT_BROWSERS_PATH="$(Agent.WorkFolder)"
            npm install --save-dev @cucumber/cucumber
            npm install --save-dev @playwright/test
            npm install --save-dev @types/cucumber
            npm install --save-dev @types/node
            npm install --save-dev chai
            npm install --save-dev cross-env
            npm install --save-dev dotenv
            npm install --save-dev fs-extra
            npm install --save-dev multiple-cucumber-html-reporter
            npm install --save-dev playwright
            npm install --save-dev ts-node
            npm install --save-dev typescript
            npm install --save-dev winston
            npx playwright install --with-deps chromium
        displayName: Package and browser installation
        

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(npm_packages_path)
          artifactName: NpmPackageArtifact
        displayName: Npm package artifact publish


      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(browser_path)
          artifactName: BrowserArtifact
        displayName: Browser artifact publish


- stage: Invoice
  dependsOn: NodeJs
  displayName: 'Invoice Test'
  jobs:
    - job: InvoiceTestJob
      displayName: 'Invoice Test Job'
      steps:


      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: NpmPackageArtifact
          targetPath: '$(Pipeline.Workspace)/s/node_modules/'
        displayName: Npm package actifact download


      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: BrowserArtifact
          targetPath: '$(Pipeline.Workspace)/s/browsers/chromium-1124/'
        displayName: Browser actifact download


      - task: PowerShell@2
        inputs:
          targetType: inline
          script: |
            $Env:PLAYWRIGHT_BROWSERS_PATH="$(Agent.WorkFolder)/1/s/browsers"
            npm test -- --tags "@Invoice"
        displayName: Test script
        env:
            CI: 'true'

  
- stage: HomeOffice
  dependsOn: NodeJs
  displayName: 'HomeOffice Test'
  jobs:
    - job: HomeOfficeJobTest
      displayName: 'HomeOffice Test Job'
      steps:
      

      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: NpmPackageArtifact
          targetPath: '$(Pipeline.Workspace)/s/node_modules/'
        displayName: Npm package actifact download


      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: BrowserArtifact
          targetPath: '$(Pipeline.Workspace)/s/browsers/chromium-1124/'
        displayName: Browser actifact download


      - task: PowerShell@2
        inputs:
          targetType: inline
          script: |
            $Env:PLAYWRIGHT_BROWSERS_PATH="$(Agent.WorkFolder)/1/s/browsers"
            npm test -- --tags "@HomeOffice"
        displayName: Test script
        env:
            CI: 'true'

