# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: windows-latest

stages:
- stage: NodeJs
  displayName: 'Install Node.js'
  jobs:
    - job: InstallJob
      displayName: 'Node.js install job'
      steps:
      ## Node.js install
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'
          checkLatest: true
      - script: |
          npm install --save-dev @cucumber/cucumber
          npm install --save-dev @playwright/test
          npm install --save-dev @types/cucumber
          npm install --save-dev @types/node
          npm install --save-dev chai
          npm install --save-dev cross-env
          npm install --save-dev dotenv
          npm install --save-dev fs-extra
          npm install --save-dev multiple-cucumber-html-reporter
          npm install --save-dev playwright
          npm install --save-dev ts-node
          npm install --save-dev typescript
          npm install --save-dev winston
          npx playwright install chrome
          npm test -- --tags "@Invoice"
        displayName: 'Install Node.js and all packages'

- stage: Invoice
  dependsOn: NodeJs
  displayName: 'Invoice Test'
  jobs:
    - job: InvoiceTestJob
      displayName: 'Invoice Test Job'
      steps:
      ## Run test
      - script: npm test -- --tags "@Invoice"
        displayName: 'Invoice Test step'
  
- stage: HomeOffice
  dependsOn: NodeJs
  displayName: 'HomeOffice Test'
  jobs:
    - job: HomeOfficeTestJob
      displayName: 'HomeOffice Test Job'
      steps:
      ## Run test
      - script: npm test -- --tags "@HomeOffice"
        displayName: 'HomeOffice Test step'       


