# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: windows-latest

stages:
- stage: NodeJs
  displayName: 'Install Node.js'
  jobs:
    - job: InstallJob
      displayName: 'Node.js install job'
      steps:
      ## Node.js install
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'
          checkLatest: true
        displayName: 'Install Node.js'

- stage: Invoice
  dependsOn: NodeJs
  displayName: 'Invoice Test'
  jobs:
    - job: InvoiceTestJob
      displayName: 'Invoice Test Job'
      steps:
      ## Run test
      - script: npm test -- --tags "@Invoice"
        displayName: 'Invoice Test step'
  
- stage: HomeOffice
  dependsOn: NodeJs
  displayName: 'HomeOffice Test'
  jobs:
    - job: HomeOfficeTestJob
      displayName: 'HomeOffice Test Job'
      steps:
      ## Run test
      - script: npm test -- --tags "@HomeOffice"
        displayName: 'HomeOffice Test step'       


