# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: windows-latest

variables:
  npm_config_cache: $(Pipeline.Workspace)/node_modules
  browser_cache: $(Pipeline.Workspace)/

stages:
- stage: NodeJs
  displayName: 'Install Node.js'
  jobs:
    - job: InstallJob
      displayName: 'Node.js install job'
      steps:
      - task: Cache@2
        inputs:
          key: 'npm | "$(Agent.OS)" | package-lock.json'
          restoreKeys: |
            npm | "$(Agent.OS)"
          path: $(npm_config_cache)
          cacheHitVar: NPM_CACHE_RESTORED
        displayName: Cache npm packages
        
      - task: Cache@2
        inputs:
          key: 'browser | "$(Agent.OS)" | package-lock.json'
          restoreKeys: |
            browser | "$(Agent.OS)"
          path: $(browser_cache)
          cacheHitVar: Browser_CACHE_RESTORED
        displayName: Cache browser download
        
      ## Node.js install
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'
          checkLatest: true

      - task: CmdLine@2
        inputs:
          script: 'tree $(Agent.WorkFolder)\1 /f'
        displayName: Current agent working directory
          
      - task: PowerShell@2
        inputs:
          targetType: inline
          script: $Env:PLAYWRIGHT_BROWSERS_PATH="$(Pipeline.Workspace)"
          
      - task: CmdLine@2
        inputs:
          script: 'tree $(Agent.WorkFolder)\1 /f'
        displayName: Current agent working directory

      - task: CmdLine@2
        inputs:
          script: |
            npm install --save-dev @cucumber/cucumber
            npm install --save-dev @playwright/test
            npm install --save-dev @types/cucumber
            npm install --save-dev @types/node
            npm install --save-dev chai
            npm install --save-dev cross-env
            npm install --save-dev dotenv
            npm install --save-dev fs-extra
            npm install --save-dev multiple-cucumber-html-reporter
            npm install --save-dev playwright
            npm install --save-dev ts-node
            npm install --save-dev typescript
            npm install --save-dev winston
            npx playwright install --with-deps chromium
            
      - task: CmdLine@2
        inputs:
          script: 'tree $(Agent.WorkFolder)\1 /f'
        displayName: Current agent working directory

- stage: Invoice
  dependsOn: NodeJs
  displayName: 'Invoice Test'
  jobs:
    - job: InvoiceTestJob
      displayName: 'Invoice Test Job'
      steps:
      - task: Npm@1
        displayName: 'Download cached dependencies'
        inputs:
          command: custom
          verbose: false
          customCommand: 'ci'
        condition: ne(variables.CACHE_RESTORED, 'true')

      ## Run test
      - script: npm test -- --tags "@Invoice"
        displayName: 'Invoice Test step'
  
- stage: HomeOffice
  dependsOn: NodeJs
  displayName: 'HomeOffice Test'
  jobs:
    - job: HomeOfficeTestJob
      displayName: 'HomeOffice Test Job'
      steps:
      ## Run test
      - task: Npm@1
        displayName: 'Download cached npm dependencies'
        inputs:
          command: custom
          verbose: false
          customCommand: 'ci'
        condition: ne(variables.CACHE_RESTORED, 'true')
        
      - script: npm test -- --tags "@HomeOffice"
        displayName: 'HomeOffice Test step'       


